a = input('digite algo \n')
print('isso é do tipo',type(a))
print('Só tem espaços?', a.isspace())
print('É um numero?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerio?', a.isalnum())
print('Esta em amiusculas?', a.isupper())
print('Eta em minusculas?', a.islower())
print('Esta captalizada', a.istitle())
